export const targetKeywords = [
  "web developer for hire",
  "best web developer for hire",
  "web developer for hire in sri lanka",
  "web developer in sri lanka",
  "best full stack developer",
  "full stack developer in sri lanka",
  "full stack developer for hire",
  "web development",
  "front end developer",
  "front end developer in sri lanka",
  "back end developer",
  "website design",
  "website design in sri lanka",
  "web design",
  "web design in sri lanka",
  "web design company",
  "web design company in sri lanka",
  "modern website",
  "modern website in sri lanka",
  "modern website designer",
  "best modern website designer",
  "best modern web design",
  "website builder",
  "best website builder in sri lanka",
  "best website builder",
  "website design templates",
  "modern website design templates",
  "best website design templates",
  "best modern website design templates",
  "web design templates",
  "modern web design templates",
  "best web design templates",
  "best modern web design templates",
  "responsive web design templates",
  "modern responsive web design templates",
  "best responsive web design templates",
  "best responsive modern web design templates",
  "responsive website design templates",
  "modern responsive website design templates",
  "best responsive website design templates",
  "best modern responsive website design templates",
  "best portfolio websites",
  "website developer near me",
  "web developer near me",
  "website designer near me",
  "professional web designer",
  "professional web designer near me",
  "web ui",
  "professional website designer",
  "professional website designer near me",
  "web dev",
  "website dev",
  "freelance web developer",
  "freelance website developer",
  "front end back end",
  "front end and back end",
  "ecommerce website development",
  "ecommerce website development near me",
  "ecommerce website designer near me",
  "ecommerce website designers near me",
  "ecommerce website design near me",
];
