export const targetKeywords = [
  "web developer for hire",
  "best web developer for hire",
  "web developer for hire in sri lanka",
  "web developer in sri lanka",
  "best full stack developer",
  "full stack developer in sri lanka",
  "full stack developer for hire",
  "web development",
  "front end developer",
  "front end developer in sri lanka",
  "back end developer",
  "website design",
  "website design in sri lanka",
  "web design",
  "web design in sri lanka",
  "web design company",
  "web design company in sri lanka",
  "modern website",
  "modern website in sri lanka",
  "modern website designer",
  "best modern website designer",
  "best modern web design",
  "website builder",
  "best website builder in sri lanka",
  "best website builder",
  "website design templates",
  "modern website design templates",
  "best website design templates",
  "best modern website design templates",
  "web design templates",
  "modern web design templates",
  "best web design templates",
  "best modern web design templates",
  "responsive web design templates",
  "modern responsive web design templates",
  "best responsive web design templates",
  "best responsive modern web design templates",
  "responsive website design templates",
  "modern responsive website design templates",
  "best responsive website design templates",
  "best modern responsive website design templates",
  "best portfolio websites",
  "website developer near me",
  "web developer near me",
  "website designer near me",
  "professional web designer",
  "professional web designer near me",
  "web ui",
  "professional website designer",
  "professional website designer near me",
  "web dev",
  "website dev",
  "freelance web developer",
  "freelance website developer",
  "front end back end",
  "front end and back end",
  "ecommerce website development",
  "ecommerce website development near me",
  "ecommerce website designer near me",
  "ecommerce website designers near me",
  "ecommerce website design near me",
  "how to create website for small business",
  "how to build a website for my business",
  "how to create a website for my business",
  "create website mobile",
  "create website mobile friendly",
  "create website responsive",
  "create website responsive design",
  "create website responsive design templates",
  "ai to create website",
  "ai to create website for me",
  "ai to create website for my business",
  "ai to create website for small business",
  "ai to create website for small business near me",
  "ai to create website for small business in sri lanka",
  "ai to create website for small business in sri lanka near me",
  "ai to create website for small business in sri lanka near me free",
  "godaddy create website",
  "how to create website",
  "create website with ai",
  "create website with ai for me",
  "create website with ai for my business",
  "create website with ai for small business",
  "shopify create website",
  "create website with shopify",
  "best church website builder",
  "best church website builder in sri lanka",
  "hostinger website builder",
  "best website builder for small business",
  "best website builder for small business in sri lanka",
  "canva website builder",
  "business website builder",
  "best business website builder",
  "best business website builder in sri lanka",
  "lms platforms",
  "best lms platforms",
  "best lms platforms in sri lanka",
  "tution class website builder",
  "best tution class website builder",
  "best tution class website builder in sri lanka",
  "tution class lms platforms",
  "best tution class lms platforms",
  "best tution class lms platforms in sri lanka",
  "best portfolio website builder",
  "best portfolio website builder in sri lanka",
  "institute website builder",
  "best institute website builder",
  "best institute website builder in sri lanka",
  "consultancy website builder",
  "best consultancy website builder",
  "best consultancy website builder in sri lanka",
  "business consultancy website builder",
  "best business consultancy website builder",
  "best business consultancy website builder in sri lanka"
];
